### ISSUE TITLE
Use STAT not fvar for access to named instances except OS/2 Weight styles

### ISSUE THREAD

**Issue by davelab6** [rosettatype/Handjet#6]
Per https://github.com/rosettatype/Handjet/issues/1#issuecomment-668730209 I'm splitting off this request into a single issue:

I want Handjet to follow [the spec the GF onboarding team recently agreed](https://github.com/googlefonts/gf-docs/tree/master/Spec?rgh-link-date=2020-08-04T14%3A01%3A17Z#axis-particles) - only have 9 `fvar` named instances for Weight 100..900, and then access to everything else named be via the `STAT` table.

**Comment by kontur** [comment]
@davelab6 A note on this since the GF recommendation will probably lead to this more often. `statmake` does not actually support writing STAT entries which are not defined as fvar instances in the first place. I've raised that [issue](https://github.com/daltonmaag/statmake/issues/36), but just pointing out that this requirement actually requires a fair bit of hacking, one way or another.

**Comment by kontur** [comment]
Note to self about fonttool's [STAT builder module](https://fonttools.readthedocs.io/en/latest/otlLib/index.html?highlight=stat#module-5). (Of course fonttools has a lib for that :D)

**Comment by RosaWagner** [comment]
Hello @kontur, for the STAT table we started to use Marc's script that you can find in [Literata](https://github.com/googlefonts/literata/blob/master/sources/gen_stat.py). You can maybe customise it for Handjet?

**Comment by kontur** [comment]
@RosaWagner cheers for the sample of `buildStatTable` in use. We have the designspace building script in the font which has all the axis stops, so it should be straight forward to adapt. 👍 
fonttools never fails to amaze :)
