### ISSUE TITLE
Include combining marks in GDEF table

### ISSUE THREAD

**Issue by davelab6** [rosettatype/Handjet#8]
In https://github.com/rosettatype/Handjet/issues/1#issuecomment-668615348 @m4rc1e said

> the combining marks are not in the gdef table. 
>
> This means they probably don't have anchors or they're not named correctly. 
>
> If we don't have these marks in the table, users won't be able to form more exotic base+mark combos.

@rosawagner noted

> All the marks that should be in the GDEF table have 0-width and anchors in the source files. Maybe the naming is not the actual nice-naming from Glyphs though.

and @MrBrezina replied

> Please, clarify if you want us to rename the mark glyphs to some other names. But I do not think the problem is there, though. Fontmake shouls not be relying on glyph names. Maybe some Glyph Info is missing in the Glyphs source?

Indeed, I believe this can be solved with either a custom `GlyphsData.xml` file, or, there is some way to include that data as a Custom Parameter Dictionary within the `.glyphs` file which `fontmake` can consume.

**Comment by kontur** [comment]
While the error feedback is valid I wonder what is the underlying issue here.

`fontmake` seems to extract the glyphs just fine and the UFO has those .glif's and they contain the appropriate anchors. However, the compiled font misses those glyphs entirely from the `GDEF` table (so not wrong group, but missing altogether).

I will investigate this further but am inclined to escalate this to `ufo2ft` since sources and UFOs seem to be "as expected".

**Comment by davelab6** [comment]
@kontur can this be closed?
